food/urls.py
from food.views import get_foods_with_type, FoodsView, ThisFoodView

app_name = "food"

from django.urls import path

urlpatterns = [
    path('food_type/<str:food_type>/', get_foods_with_type, name='this_type_foods_view'),
    path('food/<pk>', ThisFoodView.as_view(), name='get_this_food'),
    path('', FoodsView.as_view(), name='foods_view'),
]

food_order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace="orders")),
    path('management/', include('management.urls', namespace="management")),
    path('', include('food.urls', namespace="food")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'food_order.views.error_404'

orders/urls.py
from django.urls import path

from orders.views import SelectedFoodDeleteView, add_order_view, get_food_orders_view

app_name = "orders"
urlpatterns = [
    path('basket/', get_food_orders_view,name='food_order_view'),
    path('save/', add_order_view,name='save_order'),
    path("remove/<pk>/",SelectedFoodDeleteView.as_view(),name="remove_from_basket")

]

orders/models.py
import datetime

from django.db import models

# Create your models here.
from django.db.models import signals
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

from food.models import Food
from profiles.models import Profile

PAYED_METHOD = [
    ('#1', 'CASH'),
    ('#2', 'WITH CREDIT CARD'),
]


class SelectedFood(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    buyer = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="profiles_selected_food")
    quantity = models.IntegerField(default=1)
    total_price = models.FloatField()
    description = models.TextField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return str(self.food) + " | " + str(self.quantity) + "db : " + str(self.total_price)


@receiver(signals.pre_save, sender=SelectedFood)
def calculate_select_food_total_price(sender, instance, **kwargs):
    price = int(instance.quantity) * instance.food.food_price
    print("*" * 5, "receiver- quantity", instance.quantity, " food price", instance.food.food_price, "price is:", price)
    print(type(price))
    instance.total_price = price


class Orders(models.Model):
    buyer = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="buyers_orders")
    ordered_foods = models.ManyToManyField(SelectedFood)
    total_price = models.IntegerField()
    deliver_location_city = models.CharField(max_length=100)
    deliver_location_street = models.CharField(max_length=100)
    deliver_location_zip = models.IntegerField()
    comment = models.TextField(blank=True)
    payed_method = models.CharField(max_length=2, choices=PAYED_METHOD)
    created_at = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    approved_time = models.DateTimeField(blank=True, auto_now_add=False, null=True)
    expected_delivery_time = models.DateTimeField(blank=True, null=True)

    def get_ordered_foods(self):
        return self.ordered_foods.all()

    def get_absolute_path(self):
        return "/management/orders/" + str(self.pk) + "/"


@receiver(pre_save, sender=Orders)
def orders_approved(sender, instance, **kwargs):
    if instance.approved:
        instance.approved_time = datetime.datetime.now()

orders/forms.py
from django import forms

from orders.models import Orders


class OrderForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = ['payed_method','comment']

orders/views.py
from django.shortcuts import render, redirect
from django.views.generic import DeleteView
from food.models import Food
from orders.models import SelectedFood, PAYED_METHOD, Orders
from orders.utils import get_generate_uuid
from profiles.forms import ProfileForm
from profiles.models import Profile


def get_food_orders_view(request):
    print("1-------------")
    template_name = "orders/order.html"
    generate_uuid = get_generate_uuid(request)
    profile, created = Profile.objects.get_or_create(uuid=generate_uuid)
    print("**********",profile.get_my_orders())
    if request.method == 'POST':
        food = Food.objects.get(pk=request.POST['pk'])
        print("2-------------")
        this_selected_food = SelectedFood.objects.filter(buyer=profile, food=food).first()

        if this_selected_food is not None:
            this_selected_food.quantity = request.POST['food_count']
            this_selected_food.description = request.POST['food_comment']
            this_selected_food.ordered=False
            this_selected_food.save()

        else:
            this_selected_food = SelectedFood.objects.create(
                buyer=profile,
                food=food,
                description=request.POST['food_comment'],
                quantity=request.POST['food_count']
            )
        print("3-------------")
    context = {
        'basket_items': profile.get_selected_food(),
        # 'ordered_items': profile.get_under_order_food(),
        'ordered_items': profile.get_my_orders(),
        'total_price': profile.get_selected_food_total_price()
    }
    return render(request=request, context=context, template_name=template_name)


class SelectedFoodDeleteView(DeleteView):
    model = SelectedFood
    template_name = "orders/confirm.html"
    success_url = "/orders/basket/"


def this_food_is_ordered(profile):
    profile.get_selected_food().update(ordered=True)


def add_order_view(request):
    print("-------- add order view")
    template_name = "orders/saving_order.html"
    generate_uuid = get_generate_uuid(request)
    profile, created = Profile.objects.get_or_create(uuid=generate_uuid)
    saving_foods = profile.get_selected_food()
    profile_form = ProfileForm(instance=profile)


    if request.method == "POST":
        profile_form = ProfileForm(request.POST, instance=profile)
        if profile_form.is_valid():
            print("*" * 5, request.POST)
            profile_form.save()
            payment_method = request.POST['payments']
            order_comment = request.POST['order_comment']

            orders, created = Orders.objects.get_or_create(
                buyer=profile,
                payed_method=payment_method,
                deliver_location_city=profile.deliver_location_city,
                deliver_location_street=profile.deliver_location_street,
                deliver_location_zip=profile.deliver_location_zip,
                total_price=profile.get_selected_food_total_price(),
                comment=order_comment
            )

            orders.ordered_foods.add(*saving_foods)

            print("*" * 5, "adding this foods for orders", saving_foods)
            print("this is created order?", created, orders, "foods:", orders.ordered_foods)
            this_food_is_ordered(profile)
            return redirect('food:foods_view')

    context = {
        "saving_foods": saving_foods,
        "profile": profile,
        'profile_form': profile_form,
        'payed_method': PAYED_METHOD,
    }

    return render(request=request, context=context, template_name=template_name)

orders/templates/orders/confirm.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Food list {% endblock title%}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="_cardview_list">
        <div class="_cardview _cardview__long">
        <img src="{{object.food.food_pictures.url}}" alt="" class="_cardview__sm_image">
        <div class="_cardview__container">
            <div class="_cardview__title">Are you sure? <a href="" class="_link">{{object.food}}</a></div>
            <div class="_cardview__body">{{object.description}}</div>
            <div class="_cardview__footer">{{object.quantity}} DB | {{object.total_price}} FT</div>
            <button type="submit" class="_link_btn error _mt-5" data-bs-toggle="modal" data-bs-target="#showDetails{{food.pk}}">Remove</button>
        </div>
        </div>
    </div>
</form>
{% endblock content %}

orders/templates/orders/order.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}

{% block title %} | My Orders {% endblock title%}
{% block content %}
<div class="_cardview_list">

    {% for food in basket_items %}

        <form action="{% url 'orders:food_order_view'%}" method="post">
        {% csrf_token %}
        <div class="modal fade" id="showDetails{{food.pk}}" data-bs-backdrop="static"
             data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-fullscreen-xl-down">
                <div class="modal-content _modal">

                  <div class="modal-header">
                        <h5 class="modal-title _modal" id="staticBackdropLabel">Orders : {{food}}</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>

                  <div class="modal-body">
                      <div class="form-floating">
                          <textarea class="form-control" name="food_comment" id="floatingTextarea2" style="height: 100px">{{food.description|safe}}</textarea>
                          <label for="floatingTextarea2">Comments</label>
                      </div>
                      <input type="number" class="_numberInput _mt-15" name="food_count" value="{{food.quantity}}" min="1" max="10">
                  </div>

                  <div class="modal-footer">
                    <input type="hidden" name="pk" id="pk" value="{{food.food.pk}}">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Modify</button>
                  </div>
                </div>
            </div>
        </div>
        </form>



        <div class="_cardview _cardview__long _mt-15">
            <img src="{{food.food.food_pictures.url}}" alt="" class="_cardview__sm_image">
            <div class="_cardview__container">
                <div class="_cardview__title"><a href="" class="_link">{{food.food}}</a></div>
                <div class="_cardview__body">{{food.description}}</div>
                <div class="_cardview__footer">{{food.quantity}} DB | {{food.total_price}} FT</div>
                <div class="_link_btn _mt-5" data-bs-toggle="modal" data-bs-target="#showDetails{{food.pk}}">EDIT</div>
                <a class="_link_btn error _mt-5" href="{% url 'orders:remove_from_basket' pk=food.pk %}">Remove</a>
            </div>
        </div>

    {% empty %}
    <div class="inform warning">NO item in basket</div>
    {% endfor %}
</div>



    <div class="_cardview _cardview__long _mt-15 _padding-1">
            {% if basket_items %}
            <div class="_cardview__body">Total Price: {{total_price}} FT</div>
            <div class="_cardview__footer"><a class="_link_btn success _mt-15" href="{% url 'orders:save_order'%}">I AM ORDER</a></div>
            {% endif %}
    </div>

    {% if ordered_items.count > 0 %}<div class="inform _mt-15 ">This item is in progress</div>{% endif %}
<div class="_cardview_list">
    {% for order in ordered_items %}
        <div class="_cardview _cardview__long _mt-15">

            <div class="_cardview__container">
<!--                <div class="_cardview__title"><a href="" class="_link">{{food.food}}</a></div>-->
                <div class="_cardview__body">Ordered id: {{order.pk}}</div>
                <div class="_cardview__title">Order time: {{order.created_at |timezone:"Europe/Budapest"}}</div>
                <div class="_cardview__body">Approved time: {{order.approved_time|timezone:"Europe/Budapest"}}</div>
                <div class="_cardview__footer">Expected delivery time : {{order.expected_delivery_time|timezone:"Europe/Budapest"}} </div>
                <div class="_cardview__footer">Total Price : {{order.total_price}} FT </div>

                {% for food in order.get_ordered_foods %}
                <hr>
                <div class="_cardview__footer">{{food}}</div>
                {% endfor %}


            </div>
        </div>
    {% endfor %}
</div>






{% endblock content %}

orders/templates/orders/saving_order.html
{% extends 'base.html' %}
{% load static %}


{% block title %} | My Orders {% endblock title%}
{% block content %}

<div class="_cardview_list">
    <b>Your orders:</b>
    {% for food in saving_foods%}
        <div class="_cardview _cardview__long">
               {{food}} [Comment: {{food.description}}]
        </div>
    {% endfor %}
    <hr>
    <b>Total price: {{profile.get_selected_food_total_price}} FT</b>
    <br/>
    <br/>
    <br/>

    {% if saving_foods %}
    <form action="" class="_form" method="post">
        {% csrf_token %}
        {{profile_form}}
        <label for="payments">Choose Payment method:</label>

        <select id="payments" name="payments">
            {% for item in payed_method %}
              <option value="{{item.0}}">{{item.1}}</option>
            {% endfor %}
        </select>
        <laber for="order_comment">Comments</laber>
        <textarea name="order_comment" id="order_comment" placeholder="Comments"></textarea>
        <input type="submit" value="ORDER" class="_btn warning _mt-5">
    </form>
    {% else %}
    <div class="_cardview__title error">The basket is empty</div>
    {%endif%}

</div>




{% endblock content %}