food/urls.py
from food.views import get_foods_with_type, FoodsView, ThisFoodView

app_name = "food"

from django.urls import path

urlpatterns = [
    path('food_type/<str:food_type>/', get_foods_with_type, name='this_type_foods_view'),
    path('food/<pk>', ThisFoodView.as_view(), name='get_this_food'),
    path('', FoodsView.as_view(), name='foods_view'),
]

food_order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace="orders")),
    path('management/', include('management.urls', namespace="management")),
    path('', include('food.urls', namespace="food")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'food_order.views.error_404'

management/urls.py
from django.urls import path

from management.views import FoodListView, FoodUpdateView, LoginUserView, FoodOrdersView, FoodOrdersUpdateView, \
    get_new_orders_json, FoodCreateView

app_name = "management"

urlpatterns = [
    path('entry/', FoodListView.as_view(), name="management_food_list"),
    path('login/', LoginUserView.as_view(), name="login"),
    path('food_update/<pk>/', FoodUpdateView.as_view(), name="management_food_update"),
    path('orders/', FoodOrdersView.as_view(), name="management_orders"),
    path('create/', FoodCreateView.as_view(), name="management_create_food"),
    path('orders/json/', get_new_orders_json, name="management_orders_json"),
    path('orders/<pk>/', FoodOrdersUpdateView.as_view(), name="management_orders_update"),

]

orders/urls.py
from django.urls import path

from orders.views import SelectedFoodDeleteView, add_order_view, get_food_orders_view

app_name = "orders"
urlpatterns = [
    path('basket/', get_food_orders_view,name='food_order_view'),
    path('save/', add_order_view,name='save_order'),
    path("remove/<pk>/",SelectedFoodDeleteView.as_view(),name="remove_from_basket")

]

management/models.py
from django.db import models

# Create your models here.

orders/models.py
import datetime

from django.db import models

# Create your models here.
from django.db.models import signals
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

from food.models import Food
from profiles.models import Profile

PAYED_METHOD = [
    ('#1', 'CASH'),
    ('#2', 'WITH CREDIT CARD'),
]


class SelectedFood(models.Model):
    food = models.ForeignKey(Food, on_delete=models.CASCADE)
    buyer = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="profiles_selected_food")
    quantity = models.IntegerField(default=1)
    total_price = models.FloatField()
    description = models.TextField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return str(self.food) + " | " + str(self.quantity) + "db : " + str(self.total_price)


@receiver(signals.pre_save, sender=SelectedFood)
def calculate_select_food_total_price(sender, instance, **kwargs):
    price = int(instance.quantity) * instance.food.food_price
    print("*" * 5, "receiver- quantity", instance.quantity, " food price", instance.food.food_price, "price is:", price)
    print(type(price))
    instance.total_price = price


class Orders(models.Model):
    buyer = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="buyers_orders")
    ordered_foods = models.ManyToManyField(SelectedFood)
    total_price = models.IntegerField()
    deliver_location_city = models.CharField(max_length=100)
    deliver_location_street = models.CharField(max_length=100)
    deliver_location_zip = models.IntegerField()
    comment = models.TextField(blank=True)
    payed_method = models.CharField(max_length=2, choices=PAYED_METHOD)
    created_at = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    approved_time = models.DateTimeField(blank=True, auto_now_add=False, null=True)
    expected_delivery_time = models.DateTimeField(blank=True, null=True)

    def get_ordered_foods(self):
        return self.ordered_foods.all()

    def get_absolute_path(self):
        return "/management/orders/" + str(self.pk) + "/"


@receiver(pre_save, sender=Orders)
def orders_approved(sender, instance, **kwargs):
    if instance.approved:
        instance.approved_time = datetime.datetime.now()

management/forms.py
from django import forms

from orders.models import Orders


class FoodOrdersUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FoodOrdersUpdateForm, self).__init__(*args, **kwargs)
        self.fields['expected_delivery_time'].widget = forms.DateInput(attrs={'type': 'datetime-local'})
        self.fields['approved'].required = True
        self.fields['expected_delivery_time'].required = True

    class Meta:
        model = Orders
        fields = ['approved', 'expected_delivery_time']

orders/forms.py
from django import forms

from orders.models import Orders


class OrderForm(forms.ModelForm):
    class Meta:
        model = Orders
        fields = ['payed_method','comment']

management/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.views.generic import UpdateView, ListView, CreateView

from food.models import Food
from management.forms import FoodOrdersUpdateForm
from orders.models import Orders


def is_manager_members(user):
    return user.groups.filter(name="manager").exists()


class LoginUserView(LoginView):
    template_name = "management/login.html"
    model = User


class FoodListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    def test_func(self):
        return is_manager_members(self.request.user)

    login_url = '/management/login'
    redirect_field_name = '/management/entry'
    model = Food
    template_name = 'management/food_list.html'


class FoodUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    def test_func(self):
        return is_manager_members(self.request.user)

    login_url = '/management/login'
    redirect_field_name = '/management/food_update'
    model = Food
    fields = ['food_code', 'food_name', 'food_pictures', 'food_description', 'food_price', 'food_type']
    template_name = "management/food_update.html"
    success_url = "/management/entry/"


class FoodOrdersView(LoginRequiredMixin, UserPassesTestMixin, ListView):

    def test_func(self):
        return is_manager_members(self.request.user)

    login_url = '/management/login'
    redirect_field_name = '/management/orders'
    success_url = '/management/orders'
    template_name = "management/orders.html"
    model = Orders

    def get_queryset(self):
        return Orders.objects.filter(approved=False)


class FoodOrdersUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    def test_func(self):
        return is_manager_members(self.request.user)

    login_url = '/management/login'
    redirect_field_name = '/management/orders'
    model = Orders
    form_class = FoodOrdersUpdateForm
    # fields = ['approved','expected_delivery_time']
    template_name = "management/orders_update.html"
    success_url = "/management/orders"


class FoodCreateView(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    def test_func(self):
        return is_manager_members(self.request.user)

    login_url = '/management/login'
    success_url = "/management/entry/"
    model = Food
    fields = ['food_code','food_name','food_pictures','food_description','food_price','food_type']
    template_name = 'management/food_create.html'



def get_new_orders_json(request):
    data = Orders.objects.filter(approved=False)
    data_json = serializers.serialize('json',data)
    return HttpResponse(data_json,content_type='application/json')

orders/views.py
from django.shortcuts import render, redirect
from django.views.generic import DeleteView
from food.models import Food
from orders.models import SelectedFood, PAYED_METHOD, Orders
from orders.utils import get_generate_uuid
from profiles.forms import ProfileForm
from profiles.models import Profile


def get_food_orders_view(request):
    print("1-------------")
    template_name = "orders/order.html"
    generate_uuid = get_generate_uuid(request)
    profile, created = Profile.objects.get_or_create(uuid=generate_uuid)
    print("**********",profile.get_my_orders())
    if request.method == 'POST':
        food = Food.objects.get(pk=request.POST['pk'])
        print("2-------------")
        this_selected_food = SelectedFood.objects.filter(buyer=profile, food=food).first()

        if this_selected_food is not None:
            this_selected_food.quantity = request.POST['food_count']
            this_selected_food.description = request.POST['food_comment']
            this_selected_food.ordered=False
            this_selected_food.save()

        else:
            this_selected_food = SelectedFood.objects.create(
                buyer=profile,
                food=food,
                description=request.POST['food_comment'],
                quantity=request.POST['food_count']
            )
        print("3-------------")
    context = {
        'basket_items': profile.get_selected_food(),
        # 'ordered_items': profile.get_under_order_food(),
        'ordered_items': profile.get_my_orders(),
        'total_price': profile.get_selected_food_total_price()
    }
    return render(request=request, context=context, template_name=template_name)


class SelectedFoodDeleteView(DeleteView):
    model = SelectedFood
    template_name = "orders/confirm.html"
    success_url = "/orders/basket/"


def this_food_is_ordered(profile):
    profile.get_selected_food().update(ordered=True)


def add_order_view(request):
    print("-------- add order view")
    template_name = "orders/saving_order.html"
    generate_uuid = get_generate_uuid(request)
    profile, created = Profile.objects.get_or_create(uuid=generate_uuid)
    saving_foods = profile.get_selected_food()
    profile_form = ProfileForm(instance=profile)


    if request.method == "POST":
        profile_form = ProfileForm(request.POST, instance=profile)
        if profile_form.is_valid():
            print("*" * 5, request.POST)
            profile_form.save()
            payment_method = request.POST['payments']
            order_comment = request.POST['order_comment']

            orders, created = Orders.objects.get_or_create(
                buyer=profile,
                payed_method=payment_method,
                deliver_location_city=profile.deliver_location_city,
                deliver_location_street=profile.deliver_location_street,
                deliver_location_zip=profile.deliver_location_zip,
                total_price=profile.get_selected_food_total_price(),
                comment=order_comment
            )

            orders.ordered_foods.add(*saving_foods)

            print("*" * 5, "adding this foods for orders", saving_foods)
            print("this is created order?", created, orders, "foods:", orders.ordered_foods)
            this_food_is_ordered(profile)
            return redirect('food:foods_view')

    context = {
        "saving_foods": saving_foods,
        "profile": profile,
        'profile_form': profile_form,
        'payed_method': PAYED_METHOD,
    }

    return render(request=request, context=context, template_name=template_name)

management/templates/management/food_create.html
{% extends 'management_base.html' %}

{% block content %}
<h1>{{object}}</h1>
<form action="" class="_form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="_mt-5 _inform" value="ADD">
</form>
{% endblock content %}

management/templates/management/food_list.html
{% extends 'management_base.html' %}

{% block content %}
<div class="_cardview_list" >
{% for item in object_list%}
    <div class="_cardview _mt-5">
        <img src="{{item.food_pictures.url}}" alt="{{item.food}} pictures" class="_cardview__sm_image">
        <div class="_cardview__container ">
            <div class="_cardview__title"><b><a href="{% url 'management:management_food_update' pk=item.pk %}" class="_link">{{item.food_code|upper}}: </b>{{item.food_name|upper}}</a></div>
            <div class=" _mt-5">{{item.food_price}} FT</div>
            <div class="_cardview__body _mt-5 ">{{item.food_description | truncatewords:10}}</div>
        </div>
    </div>
{% endfor %}
</div>
{% endblock content %}

management/templates/management/food_update.html
{% extends 'management_base.html' %}

{% block content %}
<h1>{{object}}</h1>
<form action="" class="_form" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" class="_mt-5 _inform" value="Update">
</form>
{% endblock content %}

management/templates/management/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
login
<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Login">
</form>


</body>
</html>

management/templates/management/orders.html
{% extends 'management_base.html' %}
{% load static %}
{% load tz %}
{% block scripts %}

{% endblock scripts%}
{% block content %}

<div id="list">
{% for object in object_list%}
<!--    <h1><a href="{% url 'management:management_orders_update' pk=object.pk %}">{{object}}</a></h1>-->
    <div class="_cardview _cardview__long _mt-5" id="list">
        <div class="_cardview__container ">
            <div class="_cardview__title">
                <a class="_link" href="{{object.get_absolute_path}}">
                <b>{{object.buyer.full_name}} | {{object.buyer.email}} | {{object.buyer.phone_number}} ordered:{{object.created_at|timezone:"Europe/Budapest"|timesince}}</b>
                </a>
            </div>
            <div class="_cardview__title">
                <b>{{object.deliver_location_city}} - {{object.deliver_location_street}} | {{object.deliver_location_zip}}</b>
            </div>
            <hr>

            {% for select_food in object.get_ordered_foods %}
            <div class="_cardview__body _mt-5 ">
                {{select_food.food.food_code}} - {{select_food.food.food_name}}<br>
                {{select_food.quantity}} db<br>
                {{select_food.description}}<br>
            </div>
            <hr>
             {% endfor %}

            <div class="_cardview_footer inform">Comments:{{object.comment}}</div>
            <div class="inform _mt-5">TOTAL PRICE: {{object.total_price}} FT</div>
        </div>
    </div>
{% endfor %}
</div>

{% endblock content %}

management/templates/management/orders_update.html
{% extends 'management_base.html' %}

{% block content %}
<form action="" class="_form" method="post">
    {% csrf_token %}
    {{object}}
    {{form}}
    <input type="submit" class="_inform _mt-5" value="Approve">
</form>


{% endblock content %}