food/urls.py
from food.views import get_foods_with_type, FoodsView, ThisFoodView

app_name = "food"

from django.urls import path

urlpatterns = [
    path('food_type/<str:food_type>/', get_foods_with_type, name='this_type_foods_view'),
    path('food/<pk>', ThisFoodView.as_view(), name='get_this_food'),
    path('', FoodsView.as_view(), name='foods_view'),
]

food_order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace="orders")),
    path('management/', include('management.urls', namespace="management")),
    path('', include('food.urls', namespace="food")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'food_order.views.error_404'

management/urls.py
from django.urls import path

from management.views import FoodListView, FoodUpdateView, LoginUserView, FoodOrdersView, FoodOrdersUpdateView, \
    get_new_orders_json, FoodCreateView

app_name = "management"

urlpatterns = [
    path('entry/', FoodListView.as_view(), name="management_food_list"),
    path('login/', LoginUserView.as_view(), name="login"),
    path('food_update/<pk>/', FoodUpdateView.as_view(), name="management_food_update"),
    path('orders/', FoodOrdersView.as_view(), name="management_orders"),
    path('create/', FoodCreateView.as_view(), name="management_create_food"),
    path('orders/json/', get_new_orders_json, name="management_orders_json"),
    path('orders/<pk>/', FoodOrdersUpdateView.as_view(), name="management_orders_update"),

]

orders/urls.py
from django.urls import path

from orders.views import SelectedFoodDeleteView, add_order_view, get_food_orders_view

app_name = "orders"
urlpatterns = [
    path('basket/', get_food_orders_view,name='food_order_view'),
    path('save/', add_order_view,name='save_order'),
    path("remove/<pk>/",SelectedFoodDeleteView.as_view(),name="remove_from_basket")

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Food Orders {% block title%}{% endblock title%}</title>
    <link rel="stylesheet" href="/static/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    {% block script %}{% endblock script%}
</head>
<body>
{% include 'navbar.html' %}
<div class="_landing_menu">
    <div class="_landing_menu_container">
        <a href="{% url 'food:this_type_foods_view' '#2' %}"><img src="/static/img/design/pizza_icon.png" alt="pizza_menu_ico" class="_landing_menu_icon"></a>
        <span class="_landing_menu_title">Pizza</span>
    </div>
    <div class="_landing_menu_container">
        <a href="{% url 'food:this_type_foods_view' '#1' %}"><img src="/static/img/design/burger_icon.png" alt="burger_menu_ico" class="_landing_menu_icon"></a>
        <span class="_landing_menu_title">Hamburger</span>
    </div>
    <div class="_landing_menu_container">
        <a href="{% url 'food:this_type_foods_view' '#3' %}"><img src="/static/img/design/meal_icon.png" alt="other_meal_menu_ico" class="_landing_menu_icon"></a>
        <span class="_landing_menu_title">Other</span>
    </div>
</div>

<div class="_container">{% block content %}{% endblock content %}</div>

<header class="_header">
    <div class="_header_text_box">
        <span class="_header_text_main">Food Order and management orders</span>
        <span class="_header_text_sub">HyBase promo products</span>
    </div>
</header>


<footer class="_footer">
    <img src="/static/img/design/logo.png" class="_footer_img" alt="business logo">
    <div class="_footer_info">
        Dear. Open in every day 08am to 23pm. Order time is every day 08am to 22pm.<br>Contact tel number: +36/123-45-67
    </div>
    <ul>
        <li class="_footer_item"><a href="" class="_footer_link">Contact</a></li>
        <li class="_footer_item"><a href="mailto: hybase@outlook.hu" class="_footer_link">hybase@outlook.hu</a></li>
    </ul>
</footer>

</body>

</html>

templates/management_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block scripts %}{% endblock scripts%}
    <title>Management</title>
</head>
<body>
{% include 'management_navbar.html' %}
<div class="_container">
{% block content %}

{% endblock content %}
</div>
</body>
</html>

templates/management_navbar.html
<div class="_navbar">
    <ul>
        <li class="_navbar__items"><a href="{% url 'management:management_food_list' %}" class="_navbar__links">Menu</a></li>
        <li class="_navbar__items"><a href="{% url 'management:management_orders' %}" class="_navbar__links">Orders</a></li>
        <li class="_navbar__items"><a href="{% url 'management:management_create_food' %}" class="_navbar__links">ADD NEW FOOD</a></li>
    </ul>
</div>

templates/navbar.html
<div class="_navbar">
    <ul>
        <li class="_navbar__items"><a class="_navbar__links" href="/">Menu</a></li>
        <li class="_navbar__items"><a class="_navbar__links" href="/">Contact</a></li>
        <li class="_navbar__items"><a class="_navbar__links" href="{% url 'orders:food_order_view' %}">Basket</a></li>

    </ul>
</div>